language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION='>=1.3,<1.4'
    - DJANGO_VERSION='>=1.4,<1.5'
    - DJANGO_VERSION='>=1.5,<1.6'
matrix:
    include:
        - python: "3.3"
          env: DJANGO_VERSION='>=1.5,<1.6'
install: pip install Django$DJANGO_VERSION --use-mirrors
script: nosetests
