language: python
python:
    - "2.7"
    - "3.3"
env:
    - DJANGO_VERSION='>=1.4,<1.5'
    - DJANGO_VERSION='>=1.5,<1.6'
    - DJANGO_VERSION='>=1.6,<1.7'
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION='>=1.4,<1.5'
install:
    - pip install -q Django$DJANGO_VERSION
    - pip install -q -r test_requirements.txt
script: nosetests
